# Form implementation generated from reading ui file 'source/view/ui_files/dashboard.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import icons

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1103, 943)
        MainWindow.setStyleSheet("/* Main Window */\n"
"QMainWindow {\n"
"    background-color: #1B1B1B;\n"
"}\n"
"\n"
"/* Sidebar (Icon Only Widget) */\n"
"#icon_only_widget {\n"
"    background-color: #252A34;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"/* Labels */\n"
"QLabel {\n"
"    font-size: 14px;\n"
"    color: #F5F5F5;\n"
"    font-weight: 500;\n"
"    transition: color 0.3s ease-in-out;\n"
"}\n"
"#Icon_label {\n"
"    color: #ECF0F1;\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* Buttons */\n"
"QPushButton {\n"
"\n"
"    color: #ECF0F1;\n"
"    font-size: 14px;\n"
"    border: none;\n"
"    padding: 20px;\n"
"    width: 100%;\n"
"    transition: background-color 0.3s ease-in-out, transform 0.2s ease-in-out;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #1A252F;\n"
"    transform: scale(1.05);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #16A085;\n"
"    transform: scale(0.98);\n"
"}\n"
"QPushButton:checked {\n"
"    background-color: #16A085;\n"
"    color: #FFFFFF;\n"
"    border: 2px solid #1ABC9C;\n"
"}\n"
"\n"
"/* Specific Buttons */\n"
"#home_button_1, #earnings_button_1, #expenses_button_1, #settings_button_1, #logout_button_1, #mapper_button_1, #upload_button_1 , #change_button, #reload_button, #exit_button{\n"
"    text-align: left;\n"
"    padding-left: 12px;\n"
"    border-radius: 12px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"\n"
"#logout_button_1 {\n"
"    background-color: #D72638;\n"
"    transition: background-color 0.3s ease-in-out, transform 0.2s ease-in-out;\n"
"}\n"
"#logout_button_1:hover {\n"
"    background-color: #C0392B;\n"
"    transform: scale(1.05);\n"
"}\n"
"\n"
"/* Full Name Widget */\n"
"#full_name_widget {\n"
"    background-color: #252A34;\n"
"    padding: 12px;\n"
"    border-radius: 10px;\n"
"    transition: background-color 0.3s ease-in-out;\n"
"}\n"
"\n"
"/* ComboBox Styling */\n"
"QComboBox {\n"
"    background-color: #3A506B;\n"
"    color: #ECF0F1;\n"
"    font-size: 14px;\n"
"    border: 1px solid #1A252F;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"QComboBox:hover {\n"
"    background-color: #1A252F;\n"
"}\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"    background-color: #34495E;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #2C3E50;\n"
"    color: #ECF0F1;\n"
"    border: 1px solid #1A252F;\n"
"    selection-background-color: #16A085;\n"
"}\n"
"\n"
"/* Stacked Widget */\n"
"QStackedWidget {\n"
"    background-color: #1F1F1F;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"/* Table Widget */\n"
"QTableWidget {\n"
"    background-color: #2C3E50;\n"
"    color: #ECF0F1;\n"
"    gridline-color: #34495E;\n"
"    border: 1px solid #1A252F;\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #3A506B;\n"
"    color: #ECF0F1;\n"
"    padding: 5px;\n"
"    border: none;\n"
"}\n"
"QTableWidget::item:selected {\n"
"    background-color: #16A085;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"/* Tree Widget */\n"
"QTreeWidget {\n"
"    background-color: #2C3E50;\n"
"    color: #ECF0F1;\n"
"    border: 1px solid #1A252F;\n"
"}\n"
"QTreeWidget::item:selected {\n"
"    background-color: #16A085;\n"
"    color: #FFFFFF;\n"
"}\n"
"QTreeView::branch:selected {\n"
"    background-color: #16A085;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.icon_only_widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.icon_only_widget.setMinimumSize(QtCore.QSize(70, 0))
        self.icon_only_widget.setMaximumSize(QtCore.QSize(40, 16777215))
        self.icon_only_widget.setObjectName("icon_only_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.icon_only_widget)
        self.verticalLayout.setContentsMargins(12, 12, 16, 12)
        self.verticalLayout.setSpacing(16)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Icon_label = QtWidgets.QLabel(parent=self.icon_only_widget)
        self.Icon_label.setMinimumSize(QtCore.QSize(30, 0))
        self.Icon_label.setText("")
        self.Icon_label.setPixmap(QtGui.QPixmap(":/icons/coins.png"))
        self.Icon_label.setScaledContents(True)
        self.Icon_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Icon_label.setObjectName("Icon_label")
        self.verticalLayout.addWidget(self.Icon_label)
        self.home_button_1 = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.home_button_1.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/home.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.home_button_1.setIcon(icon)
        self.home_button_1.setIconSize(QtCore.QSize(20, 20))
        self.home_button_1.setCheckable(True)
        self.home_button_1.setAutoExclusive(True)
        self.home_button_1.setObjectName("home_button_1")
        self.verticalLayout.addWidget(self.home_button_1)
        self.earnings_button_1 = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.earnings_button_1.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/earnings.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.earnings_button_1.setIcon(icon1)
        self.earnings_button_1.setIconSize(QtCore.QSize(20, 20))
        self.earnings_button_1.setCheckable(True)
        self.earnings_button_1.setAutoExclusive(True)
        self.earnings_button_1.setObjectName("earnings_button_1")
        self.verticalLayout.addWidget(self.earnings_button_1)
        self.expenses_button_1 = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.expenses_button_1.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/expenses.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.expenses_button_1.setIcon(icon2)
        self.expenses_button_1.setIconSize(QtCore.QSize(20, 20))
        self.expenses_button_1.setCheckable(True)
        self.expenses_button_1.setAutoExclusive(True)
        self.expenses_button_1.setObjectName("expenses_button_1")
        self.verticalLayout.addWidget(self.expenses_button_1)
        self.upload_button_1 = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.upload_button_1.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/upload.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.upload_button_1.setIcon(icon3)
        self.upload_button_1.setIconSize(QtCore.QSize(20, 20))
        self.upload_button_1.setCheckable(True)
        self.upload_button_1.setAutoExclusive(True)
        self.upload_button_1.setObjectName("upload_button_1")
        self.verticalLayout.addWidget(self.upload_button_1)
        self.mapper_button_1 = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.mapper_button_1.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/mapper.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.mapper_button_1.setIcon(icon4)
        self.mapper_button_1.setIconSize(QtCore.QSize(20, 20))
        self.mapper_button_1.setCheckable(True)
        self.mapper_button_1.setAutoExclusive(True)
        self.mapper_button_1.setObjectName("mapper_button_1")
        self.verticalLayout.addWidget(self.mapper_button_1)
        spacerItem = QtWidgets.QSpacerItem(20, 433, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.settings_button_1 = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.settings_button_1.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/settings.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.settings_button_1.setIcon(icon5)
        self.settings_button_1.setIconSize(QtCore.QSize(20, 20))
        self.settings_button_1.setCheckable(True)
        self.settings_button_1.setAutoExclusive(True)
        self.settings_button_1.setObjectName("settings_button_1")
        self.verticalLayout.addWidget(self.settings_button_1)
        self.logout_button_1 = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.logout_button_1.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/logout.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.logout_button_1.setIcon(icon6)
        self.logout_button_1.setIconSize(QtCore.QSize(20, 20))
        self.logout_button_1.setCheckable(True)
        self.logout_button_1.setAutoExclusive(True)
        self.logout_button_1.setObjectName("logout_button_1")
        self.verticalLayout.addWidget(self.logout_button_1)
        self.gridLayout.addWidget(self.icon_only_widget, 0, 0, 1, 1)
        self.full_name_widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.full_name_widget.setMinimumSize(QtCore.QSize(130, 0))
        self.full_name_widget.setMaximumSize(QtCore.QSize(100, 16777215))
        self.full_name_widget.setObjectName("full_name_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.full_name_widget)
        self.verticalLayout_2.setContentsMargins(0, 12, 0, 12)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(parent=self.full_name_widget)
        self.label_3.setMinimumSize(QtCore.QSize(30, 0))
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.home_button_2 = QtWidgets.QPushButton(parent=self.full_name_widget)
        self.home_button_2.setIcon(icon)
        self.home_button_2.setCheckable(True)
        self.home_button_2.setAutoExclusive(True)
        self.home_button_2.setObjectName("home_button_2")
        self.verticalLayout_2.addWidget(self.home_button_2)
        self.earnings_button_2 = QtWidgets.QPushButton(parent=self.full_name_widget)
        self.earnings_button_2.setIcon(icon1)
        self.earnings_button_2.setCheckable(True)
        self.earnings_button_2.setAutoExclusive(True)
        self.earnings_button_2.setObjectName("earnings_button_2")
        self.verticalLayout_2.addWidget(self.earnings_button_2)
        self.expenses_button_2 = QtWidgets.QPushButton(parent=self.full_name_widget)
        self.expenses_button_2.setIcon(icon2)
        self.expenses_button_2.setCheckable(True)
        self.expenses_button_2.setAutoExclusive(True)
        self.expenses_button_2.setObjectName("expenses_button_2")
        self.verticalLayout_2.addWidget(self.expenses_button_2)
        self.upload_button_2 = QtWidgets.QPushButton(parent=self.full_name_widget)
        self.upload_button_2.setIcon(icon3)
        self.upload_button_2.setCheckable(True)
        self.upload_button_2.setAutoExclusive(True)
        self.upload_button_2.setObjectName("upload_button_2")
        self.verticalLayout_2.addWidget(self.upload_button_2)
        self.mapper_button_2 = QtWidgets.QPushButton(parent=self.full_name_widget)
        self.mapper_button_2.setIcon(icon4)
        self.mapper_button_2.setCheckable(True)
        self.mapper_button_2.setAutoExclusive(True)
        self.mapper_button_2.setObjectName("mapper_button_2")
        self.verticalLayout_2.addWidget(self.mapper_button_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 455, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.settings_button_2 = QtWidgets.QPushButton(parent=self.full_name_widget)
        self.settings_button_2.setIcon(icon5)
        self.settings_button_2.setCheckable(True)
        self.settings_button_2.setAutoExclusive(True)
        self.settings_button_2.setObjectName("settings_button_2")
        self.verticalLayout_2.addWidget(self.settings_button_2)
        self.logout_button_2 = QtWidgets.QPushButton(parent=self.full_name_widget)
        self.logout_button_2.setIcon(icon6)
        self.logout_button_2.setCheckable(True)
        self.logout_button_2.setAutoExclusive(True)
        self.logout_button_2.setObjectName("logout_button_2")
        self.verticalLayout_2.addWidget(self.logout_button_2)
        self.verticalLayout_2.setStretch(0, 4)
        self.gridLayout.addWidget(self.full_name_widget, 0, 2, 1, 1)
        self.widget_3 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget = QtWidgets.QWidget(parent=self.widget_3)
        self.widget.setMinimumSize(QtCore.QSize(0, 40))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.change_button = QtWidgets.QPushButton(parent=self.widget)
        self.change_button.setMinimumSize(QtCore.QSize(60, 0))
        self.change_button.setMaximumSize(QtCore.QSize(60, 16777215))
        self.change_button.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/nav.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.change_button.setIcon(icon7)
        self.change_button.setIconSize(QtCore.QSize(20, 20))
        self.change_button.setCheckable(True)
        self.change_button.setObjectName("change_button")
        self.horizontalLayout_2.addWidget(self.change_button)
        spacerItem2 = QtWidgets.QSpacerItem(216, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.month_combo_box = QtWidgets.QComboBox(parent=self.widget)
        self.month_combo_box.setMinimumSize(QtCore.QSize(200, 0))
        self.month_combo_box.setObjectName("month_combo_box")
        self.horizontalLayout_2.addWidget(self.month_combo_box)
        self.reload_button = QtWidgets.QPushButton(parent=self.widget)
        self.reload_button.setMaximumSize(QtCore.QSize(60, 16777215))
        self.reload_button.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/reload.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.reload_button.setIcon(icon8)
        self.reload_button.setIconSize(QtCore.QSize(40, 40))
        self.reload_button.setCheckable(False)
        self.reload_button.setObjectName("reload_button")
        self.horizontalLayout_2.addWidget(self.reload_button)
        spacerItem3 = QtWidgets.QSpacerItem(215, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.exit_button = QtWidgets.QPushButton(parent=self.widget)
        self.exit_button.setMinimumSize(QtCore.QSize(60, 0))
        self.exit_button.setMaximumSize(QtCore.QSize(60, 16777215))
        self.exit_button.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/power-off.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.exit_button.setIcon(icon9)
        self.exit_button.setIconSize(QtCore.QSize(40, 40))
        self.exit_button.setObjectName("exit_button")
        self.horizontalLayout_2.addWidget(self.exit_button)
        self.verticalLayout_3.addWidget(self.widget)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.widget_3)
        self.stackedWidget.setObjectName("stackedWidget")
        self.home_page = QtWidgets.QWidget()
        self.home_page.setObjectName("home_page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.home_page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(parent=self.home_page)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.home_page)
        self.earnings_page = QtWidgets.QWidget()
        self.earnings_page.setObjectName("earnings_page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.earnings_page)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.earnings_page)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout_3.addWidget(self.tableWidget, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.earnings_page)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.earnings_page)
        self.expenses_page = QtWidgets.QWidget()
        self.expenses_page.setObjectName("expenses_page")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.expenses_page)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tableWidget_2 = QtWidgets.QTableWidget(parent=self.expenses_page)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.gridLayout_4.addWidget(self.tableWidget_2, 2, 0, 2, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.expenses_page)
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.expenses_page)
        self.settings_page = QtWidgets.QWidget()
        self.settings_page.setObjectName("settings_page")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.settings_page)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_6 = QtWidgets.QLabel(parent=self.settings_page)
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.settings_page)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.gridLayout.addWidget(self.widget_3, 0, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.change_button.toggled['bool'].connect(self.icon_only_widget.setVisible) # type: ignore
        self.change_button.toggled['bool'].connect(self.full_name_widget.setHidden) # type: ignore
        self.home_button_1.toggled['bool'].connect(self.home_button_2.setChecked) # type: ignore
        self.earnings_button_1.toggled['bool'].connect(self.earnings_button_2.setChecked) # type: ignore
        self.expenses_button_1.toggled['bool'].connect(self.expenses_button_2.setChecked) # type: ignore
        self.settings_button_1.toggled['bool'].connect(self.settings_button_2.setChecked) # type: ignore
        self.logout_button_1.toggled['bool'].connect(self.logout_button_2.setChecked) # type: ignore
        self.home_button_2.toggled['bool'].connect(self.home_button_1.setChecked) # type: ignore
        self.earnings_button_2.toggled['bool'].connect(self.earnings_button_1.setChecked) # type: ignore
        self.expenses_button_2.toggled['bool'].connect(self.expenses_button_1.setChecked) # type: ignore
        self.settings_button_2.toggled['bool'].connect(self.settings_button_1.setChecked) # type: ignore
        self.logout_button_2.toggled['bool'].connect(self.logout_button_1.setChecked) # type: ignore
        self.exit_button.clicked.connect(MainWindow.close) # type: ignore
        self.upload_button_1.toggled['bool'].connect(self.upload_button_2.setChecked) # type: ignore
        self.mapper_button_1.toggled['bool'].connect(self.mapper_button_2.setChecked) # type: ignore
        self.upload_button_2.toggled['bool'].connect(self.upload_button_1.setChecked) # type: ignore
        self.mapper_button_2.toggled['bool'].connect(self.mapper_button_1.setChecked) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Budget Analyser"))
        self.home_button_2.setText(_translate("MainWindow", "Home"))
        self.earnings_button_2.setText(_translate("MainWindow", "Earnings"))
        self.expenses_button_2.setText(_translate("MainWindow", "Expenses"))
        self.upload_button_2.setText(_translate("MainWindow", "Upload"))
        self.mapper_button_2.setText(_translate("MainWindow", "Mapper"))
        self.settings_button_2.setText(_translate("MainWindow", "Settings"))
        self.logout_button_2.setText(_translate("MainWindow", "Logout"))
        self.label.setText(_translate("MainWindow", "Home"))
        self.label_4.setText(_translate("MainWindow", "Earnings"))
        self.label_5.setText(_translate("MainWindow", "Expenses"))
        self.label_6.setText(_translate("MainWindow", "Settings"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
