# Form implementation generated from reading ui file 'source/view/ui_files/login.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import resources_rc
import icons
from dashoard import Ui_MainWindow


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(900, 600)
        Widget.setMaximumSize(QtCore.QSize(900, 600))
        Widget.setStyleSheet("/* Main Window */\n"
"QWidget {\n"
"    background-color: #1E1E1E;  /* Dark Background */\n"
"    color: #FFFFFF;\n"
"    font-family: Arial, sans-serif;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"/* Labels */\n"
"QLabel {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"/* Line Edit (Username & Password Fields) */\n"
"QLineEdit {\n"
"    background-color: #2C2F33;\n"
"    border: 2px solid #7289DA;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"    color: white;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #99AAB5;\n"
"}\n"
"\n"
"/* Login Button */\n"
"QPushButton {\n"
"    background-color: #7289DA;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 8px;\n"
"    color: white;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5A6DAA;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4A5A9A;\n"
"}\n"
"\n"
"#label_4, #label {\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    box-shadow: 0px 0px 10px rgba(114, 137, 218, 0.5);\n"
"}\n"
"")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.central_image = QtWidgets.QLabel(parent=Widget)
        self.central_image.setMaximumSize(QtCore.QSize(550, 600))
        self.central_image.setText("")
        self.central_image.setPixmap(QtGui.QPixmap(":/images/resources/bugdet_laptop_no_bg.png"))
        self.central_image.setScaledContents(True)
        self.central_image.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.central_image.setObjectName("central_image")
        self.horizontalLayout.addWidget(self.central_image)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=Widget)
        self.label_2.setMaximumSize(QtCore.QSize(450, 16777215))
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.dollar_coin = QtWidgets.QLabel(parent=Widget)
        self.dollar_coin.setMaximumSize(QtCore.QSize(350, 350))
        self.dollar_coin.setText("")
        self.dollar_coin.setPixmap(QtGui.QPixmap(":/images/resources/dollar_coin.png"))
        self.dollar_coin.setScaledContents(True)
        self.dollar_coin.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.dollar_coin.setObjectName("dollar_coin")
        self.verticalLayout.addWidget(self.dollar_coin)
        self.label_3 = QtWidgets.QLabel(parent=Widget)
        self.label_3.setMaximumSize(QtCore.QSize(350, 16777215))
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.entered_password = QtWidgets.QLineEdit(parent=Widget)
        self.entered_password.setMaximumSize(QtCore.QSize(350, 16777215))
        self.entered_password.setObjectName("entered_password")
        self.verticalLayout.addWidget(self.entered_password)
        self.login_buttons = QtWidgets.QPushButton(parent=Widget)
        self.login_buttons.setMaximumSize(QtCore.QSize(350, 16777215))
        self.login_buttons.setObjectName("login_buttons")
        self.verticalLayout.addWidget(self.login_buttons)
        self.login_buttons.clicked.connect(self.check_password)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 4)
        self.verticalLayout.setStretch(3, 1)
        self.verticalLayout.setStretch(4, 1)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def check_password(self):
        if self.entered_password.text() == "password":  # Replace with actual password logic
            self.open_dashboard()
        else:
            QtWidgets.QMessageBox.warning(None, "Login Failed", "Incorrect Password")

    def open_dashboard(self):
        self.dashboard = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.dashboard)
        self.dashboard.show()


    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Form"))
        self.label_2.setText(_translate("Widget", "Budget Analyser"))
        self.label_3.setText(_translate("Widget", "Enter the Password"))
        self.login_buttons.setText(_translate("Widget", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Widget = QtWidgets.QWidget()
    ui = Ui_Widget()
    ui.setupUi(Widget)
    Widget.show()
    sys.exit(app.exec())
