# Form implementation generated from reading ui file 'source/view/ui_files/login.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import resources_rc


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(900, 600)
        Widget.setMaximumSize(QtCore.QSize(900, 600))
        Widget.setStyleSheet("/* Main Window */\n"
"QWidget {\n"
"    background-color: #1E1E1E;  /* Dark Background */\n"
"    color: #FFFFFF;\n"
"    font-family: Arial, sans-serif;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"/* Labels */\n"
"QLabel {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"/* Line Edit (Username & Password Fields) */\n"
"QLineEdit {\n"
"    background-color: #2C2F33;\n"
"    border: 2px solid #7289DA;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"    color: white;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #99AAB5;\n"
"}\n"
"\n"
"/* Login Button */\n"
"QPushButton {\n"
"    background-color: #7289DA;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 8px;\n"
"    color: white;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5A6DAA;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4A5A9A;\n"
"}\n"
"\n"
"#label_4, #label {\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    box-shadow: 0px 0px 10px rgba(114, 137, 218, 0.5);\n"
"}\n"
"")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(parent=Widget)
        self.label_4.setMaximumSize(QtCore.QSize(550, 600))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/DALL_E_2025-03-04_17.28.19_-_A_modern_budget_analyzer_concept_with_financial_charts__graphs__and_a_calculator_on_a_digital_screen._The_image_features_a_professional_workspace_with-removebg-preview.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=Widget)
        self.label_2.setMaximumSize(QtCore.QSize(450, 16777215))
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(parent=Widget)
        self.label.setMaximumSize(QtCore.QSize(350, 350))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/DALL_E_2025-03-04_10.59.37_-_A_detailed__realistic_gold_coin_with_intricate_engravings__embossed_edges__and_a_shiny_reflective_surface._The_coin_features_a_classic_design_with_a_f-removebg-preview.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(parent=Widget)
        self.label_3.setMaximumSize(QtCore.QSize(350, 16777215))
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.lineEdit = QtWidgets.QLineEdit(parent=Widget)
        self.lineEdit.setMaximumSize(QtCore.QSize(350, 16777215))
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(parent=Widget)
        self.pushButton.setMaximumSize(QtCore.QSize(350, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 4)
        self.verticalLayout.setStretch(3, 1)
        self.verticalLayout.setStretch(4, 1)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Form"))
        self.label_2.setText(_translate("Widget", "Budget Analyser"))
        self.label_3.setText(_translate("Widget", "Enter the Password"))
        self.pushButton.setText(_translate("Widget", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Widget = QtWidgets.QWidget()
    ui = Ui_Widget()
    ui.setupUi(Widget)
    Widget.show()
    sys.exit(app.exec())
